---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: mongodb-fromsecret
  namespace: letschat-rhacm
spec:
  namespaceSelector:
    exclude:
    - kube-*
    include:
    - letschat-rhacm
  object-templates:
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      data:
        database-admin-password: '{{ fromSecret "letschat-rhacm" "localsecret" "database-admin-password" }}'
        database-name: '{{ fromSecret "letschat-rhacm" "localsecret" "database-name" }}'
        database-password: '{{ fromSecret "letschat-rhacm" "localsecret" "database-password" }}'
        database-user: '{{ fromSecret "letschat-rhacm" "localsecret" "database-user" }}'
      kind: Secret
      metadata:
        annotations:
          template.openshift.io/expose-admin_password: '{.data[''database-admin-password'']}'
          template.openshift.io/expose-database_name: '{.data[''database-name'']}'
          template.openshift.io/expose-password: '{.data[''database-password'']}'
          template.openshift.io/expose-username: '{.data[''database-user'']}'
          apps.open-cluster-management.io/deployables: "secret"
          secretname: letschat-mongo
        labels:
          template: mongodb-ephemeral-template
        name: mongodb
      type: Opaque
  remediationAction: enforce
  severity: low

---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-shared-secret
  namespace: letschat-rhacm
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: letschat-placement
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: ConfigurationPolicy
    name: mongodb-fromsecret