---
    apiVersion: app.k8s.io/v1beta1
    kind: Application
    metadata:
      namespace: letschat-volsync
      name: letschat-volsync
    spec:
      selector:
        matchExpressions:
          - key: app
            operator: In 
            values: 
              - letschat
