---
    apiVersion: app.k8s.io/v1beta1
    kind: Application
    metadata:
      namespace: letschat-rhacm
      name: letschat-replication
    spec:
      selector:
        matchExpressions:
          - key: app
            operator: In 
            values: 
              - letschat
              - letchat-db
