---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
      app: letschat
  name: letschat-primary
  namespace: letschat-replication
spec:
  # clusters:
  #   - name: ruby
  clusterSelector:
    matchLabels:
      cluster.open-cluster-management.io/clusterset: cp4i
      letschat: 'primary'
    # matchExpressions:
    #   - key: name
    #     operator: In
    #     values: 
    #       - 'grey'
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterReplicas: 1  #Apply to how many matched clusters, default is ALL