---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: apps/letschat/letschat-full/replication/primary
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: letschat-replication
  name: letschat-primary
  namespace: letschat-replication
spec:
  channel: letschat-rhacm/letschat
  placement:
    placementRef:
      kind: PlacementRule
      name: letschat-primary
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: apps/letschat/letschat-full/replication/secondary
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: letschat-replication
  name: letschat-secondary
  namespace: letschat-replication
spec:
  channel: letschat-rhacm/letschat
  placement:
    placementRef:
      kind: PlacementRule
      name: letschat-secondary
