apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: letschat
spec:
  rsync:
    accessModes:
      - ReadWriteOnce
    capacity: 1Gi
    copyMethod: Snapshot
    serviceType: ClusterIP
    storageClassName: ocs-storagecluster-cephfs
    volumeSnapshotClassName: ocs-storagecluster-cephfsplugin-snapclass 
