apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-rhacm 
  namespace: letschat-rhacm
roleRef:
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: mongodb-rhacm
  namespace: letschat-rhacm
userNames:
- system:serviceaccount:letschat-rhacm:mongodb-rhacm
