kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: mongodb
  #namespace: letschat-volsync
spec:
  template:
    spec:
      serviceAccountName: mongodb-volsync
      securityContext:
        runAsUser: 1000712791
        fsGroup: 0
