kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-volsync
  namespace: letschat-volsync
subjects:
  - kind: ServiceAccount
    name: mongodb-volsync
    namespace: letschat-volsync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:nonroot'
