---
    apiVersion: app.k8s.io/v1beta1
    kind: Application
    metadata:
      namespace: letschat
      name: letschat
    spec:
      selector:
        matchExpressions:
          - key: app
            operator: In 
            values: 
              - letschat
