kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: mongodb
spec:
  template:
    spec:
      serviceAccountName: mongodb-rhacm
      securityContext:
        runAsUser: 1000762791
        fsGroup: 1000762791
