kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb
  labels:
    app: letschat-db
spec:
  storageClassName: san
  dataSource:
    apiGroup: ''
    kind: PersistentVolumeClaim
    name: volsync-letschat-dst
