---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: local
  namespace: letschat
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      name: local-cluster
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: ruby
  namespace: letschat
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      name: ruby