kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb
  labels:
    app: letschat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
